ant_demo/ant_demo/urls.py
from django.urls import path, include
from . import views as antviews
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.antAuth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ant_demo/apps/cms/urls.py
from django.urls import path
from .import views
from .views import release_news

app_name = 'cms'

urlpatterns = [
    path('', views.cms_index, name='cms_index'),
    # 注意，这里是将类转换为类视图，使用as_view()
    path('news/list/', views.news_list.as_view(), name='news_list'),
    path('release_news/', release_news.as_view(), name='release_news'),
    path('upload_file/', views.upload_files, name='upload_file'),
    path('qntoken/', views.qnTaken, name='qntaken'),
    path('news_category/', views.news_category_view, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('banners/', views.banners_view, name='banners'),
    path('add/banner/', views.banner_add, name='banner_add'),
    path('del/banner/', views.banner_del, name='banner_del'),
    path('edit/banner/', views.banner_edit, name='banner_edit'),
    path('banner/list/', views.banner_list, name='banner_list'),
]

ant_demo/apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('list/', views.news_list, name='news_list'),
    path('publish/comment/', views.publish_comment, name='publish_comment'),
    path('http4/', views.http4, name='http4'),
]

ant_demo/apps/cms/models.py
from django.db import models


class Banners(models.Model):
    img_url = models.URLField()
    link_to = models.URLField()
    priority = models.IntegerField(default=0, unique=True)
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'banners'
        ordering = ['-priority']

ant_demo/apps/cms/forms.py
# @Description: forms.py
# @Author: 孤烟逐云zjy
# @Date: 2020/4/1 6:33
# @SoftWare: PyCharm
# @CSDN: https://blog.csdn.net/zjy123078_zjy
# @博客园: https://www.cnblogs.com/guyan-2020/

from django import forms
from apps.forms import FormMixin
from apps.news.models import News, NewsCategory
from .models import Banners


class EditNewsCategoryForm(forms.ModelForm):
    pk = forms.IntegerField(error_messages={"required": "必须传入分类的id！"})
    category_name = forms.CharField(max_length=100)

    class Meta:
        model = NewsCategory
        fields = '__all__'

    def get_error(self):
        errors = self.errors.get_json_data()
        new_errors = {}
        for key, message_dicts in errors.items():
            messages = []
            for message_dict in message_dicts:
                message = message_dict['message']
                messages.append(message)
            new_errors[key] = messages
        return new_errors


class ReleaseForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']

        # 定义各个字段错误信息
        error_messages = {
            'title': {
                'required': '必须输入标题',
                'max_length': '最大长度不能超过200个字符',
            },
            'desc': {
                'required': '必须传入描述信息',
                'max_length': '最大的长度不能超过200个字符！',
            },
            'thumbnail': {
                'invalid': '输入的url无效',
                'required': '最大的长度不超过200个字符',
            },
        }

    def get_error(self):
        errors = self.errors.get_json_data()
        new_errors = {}
        for key, message_dicts in errors.items():
            messages = []
            for message_dict in message_dicts:
                message = message_dict['message']
                messages.append(message)
            new_errors[key] = messages
        return new_errors


class BannerForm(forms.ModelForm, FormMixin):
    class Meta:
        model = Banners
        fields = ['img_url', 'link_to', 'priority']


class EditBannerForm(forms.ModelForm, FormMixin):
    # 为了不和Django模型中的默认字段重复定义为pk
    pk = forms.IntegerField()

    class Meta:
        model = Banners
        fields = ("img_url", "link_to", "priority")

ant_demo/apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import View
from django.views.decorators.http import require_POST, require_GET
from apps.news.models import NewsCategory, News
from utils import restful
from apps.cms.forms import EditNewsCategoryForm, ReleaseForm

import os
from django.conf import settings

import qiniu

from django.conf import settings

from .forms import BannerForm, EditBannerForm
from .models import Banners
from .serializers import BannerSerializer


# 实现分页
from django.core.paginator import Paginator
from django.core.paginator import Page

# 将日期格式化
from datetime import datetime
# 将不清醒的时间转换为清醒的时间
from django.utils.timezone import make_aware

# 将参数转换为url的形式
from urllib import parse


# 后台首页视图
@staff_member_required(login_url='index')
def cms_index(request):
    return render(request, 'cms/index.html')


# 通过继承ListView实现类视图，只能够接收一个p参数，不能够接收传入的title、时间等信息
# 可以通过继承View类来实现
class news_list(View):

    def get(self, request):
        newses = News.objects.select_related("category", 'author')

        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        # request.GET获取的参数为字符串形式，在html中进行判断的时候，是整形的判断，所以需要转换为整形
        # 默认值0，只有在没有传递任何值的时候，才会使用，如果传递了空的字符串，也不会使用默认值
        category_id = int(request.GET.get('category', 0) or 0)

        # 首先筛选出符合日期的新
        if start or end:
            if start:
                startTime = datetime.strptime(start, "%Y/%m/%d")
            else:
                startTime = datetime(year=2020, month=1, day=1)
            if end:
                endTime = datetime.strptime(end, "%Y/%m/%d")
            else:
                endTime = datetime.today()

            start_time = make_aware(startTime)
            end_time = make_aware(endTime)
            newses = newses.filter(pub_time__range=(start_time, end_time))

        if title:
            newses = newses.filter(title__icontains=title)

        if category_id:
            newses = newses.filter(category=category_id)

        # 利用page函数取到newses(可以遍历的QuerySet对象，每两条数据为一页)
        pagenator = Paginator(newses, 1)
        # 拿到当前这页，如果没有传递值，默认情况下为1
        page = int(request.GET.get('p', 1))
        # 获取当前这页的对象
        page_obj = pagenator.page(page)

        context_data = self.get_pagination_data(pagenator, page_obj)

        context = {
            'categories': NewsCategory.objects.all(),
            'newses': page_obj.object_list,
            # ListView会将page_obj、pagenatior自动传递给html模板
            # View不会传递，需要手动的传递
            'pagenator': pagenator,
            'page_obj': page_obj,
            'start': start,
            'end': end,
            'category_id': category_id,
            'title': title,
            'url': '&' + parse.urlencode({
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or '',
            }),
        }
        context.update(context_data)
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page+1, num_pages+1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'num_pages': num_pages,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'current_page': current_page,
        }


# 新闻分类视图
class release_news(View):

    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories,
        }
        return render(request, 'cms/release_news.html', context=context)

    def post(self, request):
        form = ReleaseForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)

            News.objects.create(title=title, desc=desc, thumbnail=thumbnail, content=content, category=category,
                                author=request.user)
            return restful.ok()

        else:
            return restful.params_error(message=form.get_error())


@require_POST
def upload_files(request):
    # 从request.FILES中获取真实的文件，这个字典的每一个输入都是一个UploadFile对象（一个上传后的文件的简单包装）
    files = request.FILES.get('file')
    name = files.name

    # with open函数打开文件的各种方式：（默认的方式）r:以只读的方式打开；
    # w：以打开一个文件只用于写入，如果该文件已经存在，就将其覆盖。如果该文件不存在，创建新文件；
    # a：打开一个文件用于追加，如果文件存在，文件指针将会放在文件的结尾，会将新的内容写入到已有的内容之后。如果该文件不存在，创建新文件进行写入
    # rb: 以二进制格式打开一个文件用于只读。文件指针将会放在文件的开头，这是默认的模式。
    # wb：以二进制格式打开一个文件只用于写入。如果文件已经存在将其覆盖。如果该文件不存在，创建新文件。
    # ab: 以二进制格式打开一个文件用于追加。如果该文件已存在，文件指针将会放在文件的结尾。也就是说，新的内容会被写入到已有的内容之后，如果该文件不存在，创建新文件进行写入。
    # r+: 打开一个文件用于读写，文件指针将会放在文件的开头。
    # w+: 打开一个文件用于读写。如果该文件已存在，则将其覆盖。如果不存在，将创建新文件。
    # a+: 打开一个文件用于读写。如果该文件已存在，文件指针将会放在文件的结尾。文件打开时会是追加模式。如果该文件不存在，创建新文件用于读写。
    # rb+: 以二进制格式打开一个文件用于读写。文件指针将会放在文件的开头。
    # wb+: 以二进制格式打开一个文件用于读写。如果该文件已存在则将其覆盖。如果该文件不存在，创建新文件。
    # ab+: 以二进制格式打开一个文件用于追加。如果该文件已存在，文件指针将会放在文件的结尾。如果文件不存在，创建新文件用于读写。

    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        # UploadFile.read(): 从文件中读取整个上传的数据。如果文件很大，你把它读到内存中就会使系统速度减慢，
        # UploadFile.chunks(): 如果上传的文件足够大需要分块就返回真。默认这个值为2.5M, 这个值是可以调节的。
        for chunk in files.chunks():
            fp.write(chunk)
        fp.close()
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.httpResult(data={'url': url})


@require_GET
def qnTaken(request):
    access_key = settings.QINIU_ACCESS_KEY
    secret_key = settings.QINIU_SECRET_KEY

    bucket = 'cdant'
    qn = qiniu.Auth(access_key, secret_key)

    token = qn.upload_token(bucket)

    return restful.httpResult(data={'token': token})


# 新闻分类
@require_GET
def news_category_view(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'cms/news_category.html', context=context)


# 添加新闻分类
@require_POST
def add_news_category(request):
    name = request.POST.get('category_name')
    exists = NewsCategory.objects.filter(category_name=name).exists()
    if not exists:
        NewsCategory.objects.create(category_name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已经存在！')


# 编辑分类
# @require_POST
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        category_name = form.cleaned_data.get('category_name')
        exists = NewsCategory.objects.filter(category_name=category_name).exists()
        if not exists:
            NewsCategory.objects.filter(pk=pk).update(category_name=category_name)
            return restful.ok()
        else:
            return restful.params_error(message="该分类已经存在！")
    else:
        return restful.params_error(message=form.get_error())


# 删除分类
@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.params_error(message="该分类不存在！")


# 轮播图管理
def banners_view(request):
    return render(request, 'cms/banners.html')


# 轮播图列表展示
def banner_list(request):
    banners = Banners.objects.all()

    # 将QuerySet类型的数据序列化为json data
    # 指定many=True,可以将多个字段进行序列化
    serializer = BannerSerializer(banners, many=True)
    return restful.httpResult(data=serializer.data)


def banner_add(request):
    form = BannerForm(request.POST)
    if form.is_valid():
        img_url = form.cleaned_data.get('img_url')
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')

        prioExist = Banners.objects.filter(priority=priority).exists()
        if not prioExist:
            banner = Banners.objects.create(img_url=img_url, link_to=link_to, priority=priority)
            return restful.httpResult(message="轮播图信息已经添加成功了！~~~",data={'banner_id': banner.pk})
        else:
            return restful.httpResult(message="您添加的轮播图优先级已经存在了~~~")
    else:
        return restful.params_error(message=form.get_errors())


# 定义删除banner视图函数
def banner_del(request):
    banner_id = request.POST.get('banner_id')
    Banners.objects.filter(pk=banner_id).delete()
    return restful.httpResult(message="你要删除的轮播图，已经删除成功！~~ ^_^")


def banner_edit(request):
    form = EditBannerForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        img_url = form.cleaned_data.get('img_url')
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        Banners.objects.filter(pk=pk).update(img_url=img_url, link_to=link_to, priority=priority)
        return restful.httpResult(message="轮播图信息已经修改成功了！~~~")
    else:
        return restful.params_error(message=form.get_errors())

ant_demo/front/templates/cms/banners.html
{% extends 'cms/base/cms_base.html' %}

{% block title %}
    轮播图管理
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/cms/banners.min.css' %}">
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/banners.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>轮播图管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="btn-banners">
                <button class="btn btn-primary" id="add-banner-btn">
                    <i class="fa fa-plus"></i>
                    添加轮播图
                </button>
            </div>
            <ul class="tips">
                <li>支持JPG,GIF,PNG格式图片，最多可上传6张图片</li>
                <li>比例4:1，宽度在800px以上，5M以内</li>
            </ul>
        </div>
    </div>
    <div class="banner-list-group"></div>
    <script id="banner-item" type="text/html">
        {% verbatim %}
        {{ if banner }}
        <div class="box banner-item" data-banner-priority="{{ banner.priority }}" data-banner-id="{{ banner.id }}" style="width: 1000px;">
            {{ else }}
            <div class="box banner-item" style="width: 1000px;">
                {{ /if }}
                <div class="box-header">
                    {{ if banner }}
                    <span class="priority">优先级：{{ banner.priority }}</span>
                    {{ else }}
                    <span class="priority">优先级：0</span>
                    {{ /if }}
                    <button class="btn btn-default btn-xs pull-right close-btn">
                        <i class="fa fa-close"></i>
                    </button>
                </div>
                <div class="box-body">
                    <div class="thumbnail-group">
                        <input type="file" style="display: none;" class="image-input">
                        {{ if banner }}
                        <img class="thumbnail" style="width: 240px; height: 100px; float: left;"
                             src="{{ banner.img_url }}" alt="">
                        {{ else }}
                        <img class="thumbnail" style="width: 240px; height: 100px; float: left;"
                             src="http://q87jey5py.bkt.clouddn.com/1586661617709.jpg" alt="">
                        {{ /if }}
                    </div>
                    <div class="more-group" style="width: 700px; float: left;margin-left: 20px;">
                        <div class="form-group">
                            {{ if banner }}
                            <input type="number" class="form-control" name="priority" value="{{ banner.priority }}">
                            {{ else }}
                            <input type="number" class="form-control" name="priority" placeholder="图片优先级，请输入1,2...">
                            {{ /if }}
                        </div>
                        <div class="form-group">
                            {{ if banner }}
                            <input type="text" class="form-control" name="link_to" value="{{ banner.link_to }}">
                            {{ else }}
                            <input type="text" class="form-control" name="link_to" placeholder="跳转链接">
                            {{ /if }}
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <button class="btn btn-primary pull-right save-btn">保存</button>
                </div>
            </div>
        {% endverbatim %}
    </script>
{% endblock %}

ant_demo/front/templates/cms/index.html
{% extends 'cms/base/cms_base.html' %}
{% block title %}
    首页
{% endblock %}

{% block head %}

{% endblock %}

{% block content-header %}
    <h1>小蚂蚁课堂管理系统</h1>
{% endblock %}

ant_demo/front/templates/cms/news_category.html
{% extends 'cms/base/cms_base.html' %}

{% block title %}
    分类管理
{% endblock %}

{% block head %}
    <script src="{% static 'js/news_category.min.js' %}"></script>
{% endblock %}


{% block content-header %}
    <h1>分类管理</h1>

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <div class="form-group">
                        <button id="add-news-btn" class="btn btn-primary pull-right">添加分类</button>
                    </div>
                </div>
                <div class="box-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <td><strong>序号</strong></td>
                                <td><strong>分类名称</strong></td>
                                <td><strong>新闻数量</strong></td>
                                <td><strong>操作</strong></td>
                            </tr>
                            </thead>
                            <tbody>
                            {% for category in categories %}
                                <!--注意，这里的 {}动态获取的键值都需要加上双引号，否者的话，如果你的分类名称中间含有空格，就会将空格前面的显示为你的分类名称-->
                                <tr data-pk="{{ category.pk }}" data-name="{{ category.category_name }}">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ category.category_name }}</td>
                                <td>20</td>
                                <td>
                                    <button class="btn btn-warning btn-xs edit-news-btn">编辑分类</button>
                                    <button class="btn btn-danger btn-xs delete-news-btn">删除分类</button>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block sidebar-menu %}

{% endblock %}

ant_demo/front/templates/cms/news_list.html
{% extends 'cms/base/cms_base.html' %}
{% load news_filters %}

{% block title %}
    新闻列表
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/cms/news_list.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.js' %}"></script>
    <!--用来汉化的文件-->
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻列表管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="box">
            <div class="box-header">
                <form action="" class="form-inline">
                    <div class="form-group">
                        <label for="">时间：</label>
                        {% if start %}
                            <input type="text" class="form-control" id="start-picker" name="start" placeholder="起始时间"
                                   readonly value="{{ start }}">
                        {% else %}
                            <input type="text" class="form-control" id="start-picker" name="start" placeholder="起始时间"
                                   readonly>
                        {% endif %}
                        <span>-</span>
                        {% if end %}
                            <input type="text" class="form-control" id="end-picker" name="end" placeholder="结束时间"
                                   readonly value="{{ end }}">
                        {% else %}
                            <input type="text" class="form-control" id="end-picker" name="end" placeholder="结束时间"
                                   readonly>
                        {% endif %}
                    </div>
                    <div class="form-group left-group">
                        <label for="primary-title">标题：</label>
                        {% if title %}
                            <input type="text" class="form-control" name="title" placeholder="请输入标题关键字"
                                   value="{{ title }}">
                        {% else %}
                            <input type="text" class="form-control" name="title" placeholder="请输入标题关键字">
                        {% endif %}
                    </div>
                    <div class="form-group left-group">
                        <label for="category-group">分类：</label>
                        <select name="category" id="category-group" class="form-control">
                            {% if category_id %}
                                <option value="0" selected>所有分类</option>
                            {% else %}
                                <!--默认情况下，选择所有分类-->
                                <option value="0">所有分类</option>
                            {% endif %}

                            {% for category in categories %}
                                {% if category_id == category.pk %}
                                    <option value="{{ category.pk }}" selected>{{ category.category_name }}</option>
                                {% else %}
                                    <option value="{{ category.pk }}">{{ category.category_name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group left-group">
                        <button class="btn btn-primary">
                            搜索
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                    <div class="form-group left-group">
                        <a href="{% url 'cms:news_list' %}">清除查询条件</a>
                    </div>
                </form>
            </div>
            <div class="box-body">
                <!--table代表的是使用AdminLTE中的表格，table-bordered代表的是有表格线-->
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>标题</th>
                        <th>分类</th>
                        <th>发布时间</th>
                        <th>作者</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for news in newses %}
                        <tr>
                            <td><a target="_blank"
                                   href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a></td>
                            <td>{{ news.category.category_name }}</td>
                            <td>{{ news.pub_time|time_format }}</td>
                            <td>{{ news.author.username }}</td>
                            <td>
                                <!--可以跳转的a标签，但是颜色是按钮的颜色（提示性颜色），点击的时候会重新打开新的空白页-->
                                <!--btn-xs代表的是小型的按钮-->
                                <a target="_blank" href="" class="btn btn-info btn-xs">编辑</a>
                                <button class="btn btn-danger btn-xs">删除</button>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class="box-footer">
                <p class="pull-left">第{{ current_page }}页/总共{{ num_pages }}页</p>
                <ul class="pagination pull-right">
                    {# 上一页 #}
                    {% if page_obj.has_previous %}
                        <li><a href="?p={{ page_obj.previous_page_number }}{{ url }}">上一页</a></li>
                    {% else %}
                        <li class="disabled"><a href="javascript: void(0);">上一页</a></li>
                    {% endif %}

                    {% if left_has_more %}
                        <li><a href="?p=1{{ url }}">1</a></li>
                        <li><a href="javascript:void(0);">...</a></li>
                    {% endif %}

                    {# 中间页 #}
                    {#  left页  #}
                    {% for left_page in left_pages %}
                        <li><a href="?p={{ left_page }}{{ url }}">{{ left_page }}</a></li>
                    {% endfor %}

                    {#  当前页  #}
                    <li class="active"><a href="?p={{ current_page }}{{ url }}">{{ current_page }}</a></li>

                    {#  right页  #}
                    {% for right_page in right_pages %}
                        <li><a href="?p={{ right_page }}{{ url }}">{{ right_page }}</a></li>
                    {% endfor %}

                    {% if right_has_more %}
                        <li><a href="javascript:void(0);">...</a></li>
                        <li><a href="?p={{ num_pages }}{{ url }}">{{ num_pages }}</a></li>
                    {% endif %}


                    {# 下一页 #}
                    {% if page_obj.has_next %}
                        <li><a href="?p={{ page_obj.next_page_number }}{{ url }}">下一页</a></li>
                    {% else %}
                        <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}