ant_demo/ant_demo/urls.py
from django.urls import path, include
from . import views as antviews
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.antAuth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ant_demo/apps/cms/urls.py
from django.urls import path
from .import views
from .views import release_news

app_name = 'cms'

urlpatterns = [
    path('', views.cms_index, name='cms_index'),
    # 注意，这里是将类转换为类视图，使用as_view()
    path('news/list/', views.news_list.as_view(), name='news_list'),
    path('release_news/', release_news.as_view(), name='release_news'),
    path('upload_file/', views.upload_files, name='upload_file'),
    path('qntoken/', views.qnTaken, name='qntaken'),
    path('news_category/', views.news_category_view, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('banners/', views.banners_view, name='banners'),
    path('add/banner/', views.banner_add, name='banner_add'),
    path('del/banner/', views.banner_del, name='banner_del'),
    path('edit/banner/', views.banner_edit, name='banner_edit'),
    path('banner/list/', views.banner_list, name='banner_list'),
]

ant_demo/apps/cms/models.py
from django.db import models


class Banners(models.Model):
    img_url = models.URLField()
    link_to = models.URLField()
    priority = models.IntegerField(default=0, unique=True)
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'banners'
        ordering = ['-priority']

ant_demo/apps/cms/forms.py
# @Description: forms.py
# @Author: 孤烟逐云zjy
# @Date: 2020/4/1 6:33
# @SoftWare: PyCharm
# @CSDN: https://blog.csdn.net/zjy123078_zjy
# @博客园: https://www.cnblogs.com/guyan-2020/

from django import forms
from apps.forms import FormMixin
from apps.news.models import News, NewsCategory
from .models import Banners


class EditNewsCategoryForm(forms.ModelForm):
    pk = forms.IntegerField(error_messages={"required": "必须传入分类的id！"})
    category_name = forms.CharField(max_length=100)

    class Meta:
        model = NewsCategory
        fields = '__all__'

    def get_error(self):
        errors = self.errors.get_json_data()
        new_errors = {}
        for key, message_dicts in errors.items():
            messages = []
            for message_dict in message_dicts:
                message = message_dict['message']
                messages.append(message)
            new_errors[key] = messages
        return new_errors


class ReleaseForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']

        # 定义各个字段错误信息
        error_messages = {
            'title': {
                'required': '必须输入标题',
                'max_length': '最大长度不能超过200个字符',
            },
            'desc': {
                'required': '必须传入描述信息',
                'max_length': '最大的长度不能超过200个字符！',
            },
            'thumbnail': {
                'invalid': '输入的url无效',
                'required': '最大的长度不超过200个字符',
            },
        }

    def get_error(self):
        errors = self.errors.get_json_data()
        new_errors = {}
        for key, message_dicts in errors.items():
            messages = []
            for message_dict in message_dicts:
                message = message_dict['message']
                messages.append(message)
            new_errors[key] = messages
        return new_errors


class BannerForm(forms.ModelForm, FormMixin):
    class Meta:
        model = Banners
        fields = ['img_url', 'link_to', 'priority']


class EditBannerForm(forms.ModelForm, FormMixin):
    # 为了不和Django模型中的默认字段重复定义为pk
    pk = forms.IntegerField()

    class Meta:
        model = Banners
        fields = ("img_url", "link_to", "priority")

ant_demo/apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import View
from django.views.decorators.http import require_POST, require_GET
from apps.news.models import NewsCategory, News
from utils import restful
from apps.cms.forms import EditNewsCategoryForm, ReleaseForm

import os
from django.conf import settings

import qiniu

from django.conf import settings

from .forms import BannerForm, EditBannerForm
from .models import Banners
from .serializers import BannerSerializer


# 实现分页
from django.core.paginator import Paginator
from django.core.paginator import Page

# 将日期格式化
from datetime import datetime
# 将不清醒的时间转换为清醒的时间
from django.utils.timezone import make_aware

# 将参数转换为url的形式
from urllib import parse


# 后台首页视图
@staff_member_required(login_url='index')
def cms_index(request):
    return render(request, 'cms/index.html')


# 通过继承ListView实现类视图，只能够接收一个p参数，不能够接收传入的title、时间等信息
# 可以通过继承View类来实现
class news_list(View):

    def get(self, request):
        newses = News.objects.select_related("category", 'author')

        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        # request.GET获取的参数为字符串形式，在html中进行判断的时候，是整形的判断，所以需要转换为整形
        # 默认值0，只有在没有传递任何值的时候，才会使用，如果传递了空的字符串，也不会使用默认值
        category_id = int(request.GET.get('category', 0) or 0)

        # 首先筛选出符合日期的新
        if start or end:
            if start:
                startTime = datetime.strptime(start, "%Y/%m/%d")
            else:
                startTime = datetime(year=2020, month=1, day=1)
            if end:
                endTime = datetime.strptime(end, "%Y/%m/%d")
            else:
                endTime = datetime.today()

            start_time = make_aware(startTime)
            end_time = make_aware(endTime)
            newses = newses.filter(pub_time__range=(start_time, end_time))

        if title:
            newses = newses.filter(title__icontains=title)

        if category_id:
            newses = newses.filter(category=category_id)

        # 利用page函数取到newses(可以遍历的QuerySet对象，每两条数据为一页)
        pagenator = Paginator(newses, 1)
        # 拿到当前这页，如果没有传递值，默认情况下为1
        page = int(request.GET.get('p', 1))
        # 获取当前这页的对象
        page_obj = pagenator.page(page)

        context_data = self.get_pagination_data(pagenator, page_obj)

        context = {
            'categories': NewsCategory.objects.all(),
            'newses': page_obj.object_list,
            # ListView会将page_obj、pagenatior自动传递给html模板
            # View不会传递，需要手动的传递
            'pagenator': pagenator,
            'page_obj': page_obj,
            'start': start,
            'end': end,
            'category_id': category_id,
            'title': title,
            'url': '&' + parse.urlencode({
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or '',
            }),
        }
        context.update(context_data)
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page+1, num_pages+1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'num_pages': num_pages,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'current_page': current_page,
        }


# 新闻分类视图
class release_news(View):

    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories,
        }
        return render(request, 'cms/release_news.html', context=context)

    def post(self, request):
        form = ReleaseForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)

            News.objects.create(title=title, desc=desc, thumbnail=thumbnail, content=content, category=category,
                                author=request.user)
            return restful.ok()

        else:
            return restful.params_error(message=form.get_error())


@require_POST
def upload_files(request):
    # 从request.FILES中获取真实的文件，这个字典的每一个输入都是一个UploadFile对象（一个上传后的文件的简单包装）
    files = request.FILES.get('file')
    name = files.name

    # with open函数打开文件的各种方式：（默认的方式）r:以只读的方式打开；
    # w：以打开一个文件只用于写入，如果该文件已经存在，就将其覆盖。如果该文件不存在，创建新文件；
    # a：打开一个文件用于追加，如果文件存在，文件指针将会放在文件的结尾，会将新的内容写入到已有的内容之后。如果该文件不存在，创建新文件进行写入
    # rb: 以二进制格式打开一个文件用于只读。文件指针将会放在文件的开头，这是默认的模式。
    # wb：以二进制格式打开一个文件只用于写入。如果文件已经存在将其覆盖。如果该文件不存在，创建新文件。
    # ab: 以二进制格式打开一个文件用于追加。如果该文件已存在，文件指针将会放在文件的结尾。也就是说，新的内容会被写入到已有的内容之后，如果该文件不存在，创建新文件进行写入。
    # r+: 打开一个文件用于读写，文件指针将会放在文件的开头。
    # w+: 打开一个文件用于读写。如果该文件已存在，则将其覆盖。如果不存在，将创建新文件。
    # a+: 打开一个文件用于读写。如果该文件已存在，文件指针将会放在文件的结尾。文件打开时会是追加模式。如果该文件不存在，创建新文件用于读写。
    # rb+: 以二进制格式打开一个文件用于读写。文件指针将会放在文件的开头。
    # wb+: 以二进制格式打开一个文件用于读写。如果该文件已存在则将其覆盖。如果该文件不存在，创建新文件。
    # ab+: 以二进制格式打开一个文件用于追加。如果该文件已存在，文件指针将会放在文件的结尾。如果文件不存在，创建新文件用于读写。

    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        # UploadFile.read(): 从文件中读取整个上传的数据。如果文件很大，你把它读到内存中就会使系统速度减慢，
        # UploadFile.chunks(): 如果上传的文件足够大需要分块就返回真。默认这个值为2.5M, 这个值是可以调节的。
        for chunk in files.chunks():
            fp.write(chunk)
        fp.close()
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.httpResult(data={'url': url})


@require_GET
def qnTaken(request):
    access_key = settings.QINIU_ACCESS_KEY
    secret_key = settings.QINIU_SECRET_KEY

    bucket = 'cdant'
    qn = qiniu.Auth(access_key, secret_key)

    token = qn.upload_token(bucket)

    return restful.httpResult(data={'token': token})


# 新闻分类
@require_GET
def news_category_view(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'cms/news_category.html', context=context)


# 添加新闻分类
@require_POST
def add_news_category(request):
    name = request.POST.get('category_name')
    exists = NewsCategory.objects.filter(category_name=name).exists()
    if not exists:
        NewsCategory.objects.create(category_name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已经存在！')


# 编辑分类
# @require_POST
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        category_name = form.cleaned_data.get('category_name')
        exists = NewsCategory.objects.filter(category_name=category_name).exists()
        if not exists:
            NewsCategory.objects.filter(pk=pk).update(category_name=category_name)
            return restful.ok()
        else:
            return restful.params_error(message="该分类已经存在！")
    else:
        return restful.params_error(message=form.get_error())


# 删除分类
@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.params_error(message="该分类不存在！")


# 轮播图管理
def banners_view(request):
    return render(request, 'cms/banners.html')


# 轮播图列表展示
def banner_list(request):
    banners = Banners.objects.all()

    # 将QuerySet类型的数据序列化为json data
    # 指定many=True,可以将多个字段进行序列化
    serializer = BannerSerializer(banners, many=True)
    return restful.httpResult(data=serializer.data)


def banner_add(request):
    form = BannerForm(request.POST)
    if form.is_valid():
        img_url = form.cleaned_data.get('img_url')
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')

        prioExist = Banners.objects.filter(priority=priority).exists()
        if not prioExist:
            banner = Banners.objects.create(img_url=img_url, link_to=link_to, priority=priority)
            return restful.httpResult(message="轮播图信息已经添加成功了！~~~",data={'banner_id': banner.pk})
        else:
            return restful.httpResult(message="您添加的轮播图优先级已经存在了~~~")
    else:
        return restful.params_error(message=form.get_errors())


# 定义删除banner视图函数
def banner_del(request):
    banner_id = request.POST.get('banner_id')
    Banners.objects.filter(pk=banner_id).delete()
    return restful.httpResult(message="你要删除的轮播图，已经删除成功！~~ ^_^")


def banner_edit(request):
    form = EditBannerForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        img_url = form.cleaned_data.get('img_url')
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        Banners.objects.filter(pk=pk).update(img_url=img_url, link_to=link_to, priority=priority)
        return restful.httpResult(message="轮播图信息已经修改成功了！~~~")
    else:
        return restful.params_error(message=form.get_errors())

ant_demo/front/templates/cms/base/cms_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}| 小蚂蚁管理系统</title>

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1347266_1120imkhssrc.css">
    <link rel="shortcut icon" href="{% static "images/favicon.min.ico" %}"/>
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/skins/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/maxcdn/html5shiv/html5shiv.min.js' %}"></script>
    <script src="{% static 'adminlte/maxcdn/respond/respond.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/adminlte/js/adminlte.min.js' %}"></script>
    <script src="{% static 'js/adminlte/js/demo.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/antajax.min.js' %}"></script>
    <script src="{% static 'js/antalert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <a href="#" class="logo">
            <span class="logo-mini"><b>蚂蚁</b></span>
            <span class="logo-lg"><b>小蚂蚁</b>管理系统</span>
        </a>
        <nav class="navbar navbar-static-top">
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static 'images/avatar/avatar7.jpg' %}" class="user-image"
                                 alt="User Image">
                            <span class="hidden-xs">孤烟逐云zjy</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <img src="{% static 'images/avatar/avatar7.jpg' %}" class="img-circle" alt="User Image"
                                     style="width: 80px; height: 80px; border-radius: 50%">
                                <p>
                                    孤烟逐云zjy - Web Developer
                                    <small>Member since Nov. 2019</small>
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <section class="sidebar">
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{% static 'images/avatar/avatar7.jpg' %}" class="img-circle" alt="User Image" style="width: 40px; height: 40px; border-radius: 50%">
                </div>
                <div class="pull-left info">
                    <p>孤烟逐云zjy</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="搜索">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
                </div>
            </form>
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:cms_index' %}">
                        <i class="fa  fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
            <li class="header">新闻管理</li>
            <li>
                <a href="{% url 'cms:news_list' %}">
                    <i class="fa fa-list"></i>
                    <span>新闻列表</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cms:release_news' %}">
                    <i class="fa fa-edit"></i>
                    <span>发布最新</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cms:news_category' %}">
                    <i class="fa fa-tags"></i>
                    <span>新闻分类</span>
                </a>
            </li>
            <li>
                <a href="{% url 'cms:banners'%}">
                    <i class="fa fa-window-restore"></i>
                    <span>轮播图管理</span>
                </a>
            </li>
                {% block sidebar-menu %}{% endblock %}
            </ul>
        </section>
    </aside>
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>

        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 2.4.18
        </div>
        <strong>Copyright &copy; 2019-2020 <b>小蚂蚁课堂</b></strong> All rights reserved.
    </footer>
    <div class="control-sidebar-bg"></div>
</div>
</body>
</html>