ant_demo/ant_demo/urls.py
from django.urls import path, include
from . import views as antviews
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.antAuth.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ant_demo/apps/antAuth/urls.py
from django.urls import path
from . import views

app_name = "antAuth"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_Captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_sender, name='sms_captcha'),
    path('register/', views.register_view, name='register'),
    path('cache/', views.cache_test, name='cache'),
]

ant_demo/apps/cms/urls.py
from django.urls import path
from .import views
from .views import release_news

app_name = 'cms'

urlpatterns = [
    path('', views.cms_index, name='cms_index'),
    # 注意，这里是将类转换为类视图，使用as_view()
    path('news/list/', views.news_list.as_view(), name='news_list'),
    path('release_news/', release_news.as_view(), name='release_news'),
    path('upload_file/', views.upload_files, name='upload_file'),
    path('qntoken/', views.qnTaken, name='qntaken'),
    path('news_category/', views.news_category_view, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('banners/', views.banners_view, name='banners'),
    path('add/banner/', views.banner_add, name='banner_add'),
    path('del/banner/', views.banner_del, name='banner_del'),
    path('edit/banner/', views.banner_edit, name='banner_edit'),
    path('banner/list/', views.banner_list, name='banner_list'),
]

ant_demo/front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/common/auth.min.css" %}">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1347266_1120imkhssrc.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1347266_6jobx7n49pd.css">
    <link rel="shortcut icon" href="{% static "images/favicon.min.ico" %}"/>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static "js/antajax.min.js" %}"></script>
    <script src="{% static 'js/FrontBaseHeader.min.js' %}"></script>
    {% block header %}{% endblock %}
</head>
<body>
<div class="header">
    <div class="contain">
        <div class="logo-box">
            <i class="icon-Txu iconfont"></i>
            <i class="icon-Txu iconfont"></i>
        </div>
        <ul class="nav">
            <li class="active"><a href="/">首页</a></li>
            <li><a href="#">资讯</a></li>
            <li><a href="#">创业课堂</a></li>
            <li><a href="#">服务大厅</a></li>
            <li><a href="#">联系我们</a></li>
            <li><a href="#">搜索</a></li>
        </ul>
        <div class="auth-box">
            <i class="icon-person iconfont"></i>
            <!--在django项目的settings.py文件中，有一个auth的上下文处理器，上下文处理器主要是为了向模板中传递参数的，该上下文处理器会创建一个user的变量-->
            <!--user对象上的is_authenticated方法用来判断，用户是否登录成功了，如果登录成功，就会返回True，否者的话，就会返回False。-->
            {% if user.is_authenticated %}
                <a href="#" class="authenticated-box">{{ user.username }}</a>
                <div class="user-more-box">
                    <i class="triangle"></i>
                    {% if user.is_superuser %}
                        <a href="{% url 'cms:cms_index' %}">管理系统</a>
                    {% endif %}
                    <a href="{% url 'antAuth:logout' %}">退出登录</a>
                </div>
            {% else %}
                <a href="#" class="signin-btn">登录</a> /
                <a href="#" class="signup-btn">注册</a>
            {% endif %}
        </div>
    </div>
</div>
{% block main %}{% endblock %}
<div class="footer">
    <div class="footer-top-group">
        <div class="footer-main">
            <div class="logo-box">
                <i class="icon-Txu iconfont"></i>
                <i class="icon-Txu iconfont"></i>
            </div>
            <div class="detail-group">
                <div class="line1-group">
                    <ul class="link">
                        <li><a href="#">关于小蚂蚁</a></li>
                        <li><a href="#">创业课堂</a></li>
                        <li><a href="#">寻求报道</a></li>
                        <li><a href="#">礼包</a></li>
                    </ul>
                    <div class="focus-us">
                        <p class="focus">关于我们：</p>
                        <ul class="social-group">
                            <li class="ant-weixin">
                                <span class="weixin">小蚂蚁公众号</span>
                                <div class="weixin-qrcode"></div>
                            </li>
                            <li class="ant-weibo"><a href="#" class="weibo">小蚂蚁微博</a></li>
                        </ul>
                    </div>
                </div>
                <div class="line2-group">
                    <p class="address">地址：吉林省长春市卫星广场6543号长春大学东校区</p>
                    <p class="contect-us">联系我们：0431-888855632</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom-group">
        ©2020 吉林省长春市卫星广场6543号长春大学东校区小蚂蚁课堂
    </div>
</div>
<div class="mask-wrapper">
    <div class="auth-group">
        <div class="close-group">
            <span class="closeBtn icon-baseline-close-px iconfont"></span>
        </div>
        <div class="auth-scroll-wrapper">
            <div class="scroll-wrapper">
                <div class="auth-group signin-group">
                    <div class="auth-info">
                        <div class="title-group">
                            <span class="title">请登录</span>
                            <a href="javascript: void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <label class="remember-label">
                                    <input type="checkbox" name="remember" value="1"> 记住我
                                </label>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" name="submit" value="立即登录">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="auth-group signup-group">
                    <div class="auth-info">
                        <div class="title-group">
                            <span class="title">请注册</span>
                            <a href="javascript: void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="请输入手机号">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="请输入用户名">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="password" placeholder="请输入密码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="repeat_password" placeholder="确认密码">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="input-group-addon">
                                    <img src="{% url 'antAuth:img_captcha' %}" alt="" class="img_captcha"
                                         style="cursor:pointer;">
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                                </div>
                                <div class="input-group-addon">
                                    <span class="sms-captcha-btn">发送验证码</span>
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即注册">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>